name: upload

on:
  push:
    branches: [ 672 ]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 672

      - name: env setup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          #sudo -E apt update
          #sudo -E apt install containerd docker.io wget -y
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
      - name: build 
        run: |
          cd ../
          sudo -E git clone https://github.com/zerofo/docker-8266-builder
          cd docker-8266-builder;
          sudo sed -i "s/-it/-i/g" runsd.sh 
          sudo mkdir -p output
          sudo sed -i "s/\$\(pwd\)\/:\/output/\.\/output/g" runsd.sh 
          sudo -E bash runsd.sh ../zerofo.github.io
      - name: upload binfile
        uses: actions/upload-artifact@v2
        with:
          name: 8266_bin
          path: ./*.zip
